# Generated by Django 3.1.7 on 2021-03-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Display type')),
                ('resolution', models.CharField(max_length=255, verbose_name='Resolution')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Accum volume')),
                ('ram', models.CharField(max_length=255, verbose_name='Ram')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume', models.CharField(max_length=255, verbose_name='SD volume')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Main cam max resolution')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Frontal cam max resolution')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product name')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Display type')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Processor freq')),
                ('ram', models.CharField(max_length=255, verbose_name='Ram')),
                ('video', models.CharField(max_length=255, verbose_name='Graphics card')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Battery life')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
